Repository andrei1058/BedWars1058, pull requests merged in 2021-12, with the labels that each got.

#176 Fireball knockback (configurable)
  bedwars-api/src/main/java/com/andrei1058/bedwars/api/arena/IArena.java
  bedwars-api/src/main/java/com/andrei1058/bedwars/api/configuration/ConfigPath.java
  bedwars-plugin/src/main/java/com/andrei1058/bedwars/BedWars.java
  bedwars-plugin/src/main/java/com/andrei1058/bedwars/arena/Arena.java
  bedwars-plugin/src/main/java/com/andrei1058/bedwars/configuration/MainConfig.java
  bedwars-plugin/src/main/java/com/andrei1058/bedwars/listeners/BreakPlace.java
  bedwars-plugin/src/main/java/com/andrei1058/bedwars/listeners/DamageDeathMove.java
  bedwars-plugin/src/main/java/com/andrei1058/bedwars/listeners/FireballListener.java
  bedwars-plugin/src/main/java/com/andrei1058/bedwars/listeners/Interact.java
Labels: requires-changes

#151 Clear arrows from player's body on death (FIXED)
  bedwars-api/src/main/java/com/andrei1058/bedwars/api/server/VersionSupport.java
  bedwars-plugin/src/main/java/com/andrei1058/bedwars/listeners/DamageDeathMove.java
  versionsupport_1_10_R1/src/main/java/com/andrei1058/bedwars/support/version/v1_10_R1/v1_10_R1.java
  versionsupport_1_11_R1/src/main/java/com/andrei1058/bedwars/support/version/v1_11_R1/v1_11_R1.java
  versionsupport_1_12_R1/src/main/java/com/andrei1058/bedwars/support/version/v1_12_R1/v1_12_R1.java
  versionsupport_1_13_R2/src/main/java/com/andrei1058/bedwars/support/version/v1_13_R2/v1_13_R2.java
  versionsupport_1_14_R1/src/main/java/com/andrei1058/bedwars/support/version/v1_14_R1/v1_14_R1.java
  versionsupport_1_15_R1/src/main/java/com/andrei1058/bedwars/support/version/v1_15_R1/v1_15_R1.java
  versionsupport_1_16_R1/src/main/java/com/andrei1058/bedwars/support/version/v1_16_R1/v1_16_R1.java
  versionsupport_1_16_R2/src/main/java/com/andrei1058/bedwars/support/version/v1_16_R2/v1_16_R2.java
  versionsupport_1_8_R3/src/main/java/com/andrei1058/bedwars/support/version/v1_8_R3/v1_8_R3.java
  versionsupport_1_9_R2/src/main/java/com/andrei1058/bedwars/support/version/v1_9_R2/v1_9_R2.java
  versionsupport_v1_16_R3/src/main/java/com/andrei1058/bedwars/support/version/v1_16_R3/v1_16_R3.java
  versionsupport_v1_17_R1/src/main/java/com/andrei1058/bedwars/support/version/v1_17_R1/v1_17_R1.java
  versionsupport_v1_18_R1/src/main/java/com/andrei1058/bedwars/support/version/v1_18_R1/v1_18_R1.java
Labels: needs-testing

#155 PAPI support to items
  bedwars-plugin/src/main/java/com/andrei1058/bedwars/arena/Arena.java
  bedwars-plugin/src/main/java/com/andrei1058/bedwars/support/papi/SupportPAPI.java
Labels: question

#190 Quick shop add item inventory title's missing language
  bedwars-api/src/main/java/com/andrei1058/bedwars/api/language/Messages.java
  bedwars-plugin/src/main/java/com/andrei1058/bedwars/language/Bangla.java
  bedwars-plugin/src/main/java/com/andrei1058/bedwars/language/English.java
  bedwars-plugin/src/main/java/com/andrei1058/bedwars/language/Italian.java
  bedwars-plugin/src/main/java/com/andrei1058/bedwars/language/Persian.java
  bedwars-plugin/src/main/java/com/andrei1058/bedwars/language/Polish.java
  bedwars-plugin/src/main/java/com/andrei1058/bedwars/language/Romanian.java
  bedwars-plugin/src/main/java/com/andrei1058/bedwars/language/Russian.java
  bedwars-plugin/src/main/java/com/andrei1058/bedwars/language/Spanish.java
  bedwars-plugin/src/main/java/com/andrei1058/bedwars/shop/quickbuy/QuickBuyAdd.java
Labels: needs-review
