Repository andrei1058/BedWars1058, pull requests merged in 2021-11, with the labels that each got.

#15 Update Spanish.java
  bedwars-plugin/src/main/java/com/andrei1058/bedwars/language/Spanish.java
Labels: needs-testing

#50 Added Bangla Language
  bedwars-plugin/src/main/java/com/andrei1058/bedwars/BedWars.java
  bedwars-plugin/src/main/java/com/andrei1058/bedwars/language/Bangla.java
Labels: requires-changes

#115 Fix subtitle not being cleared
  versionsupport_1_10_R1/src/main/java/com/andrei1058/bedwars/support/version/v1_10_R1/v1_10_R1.java
  versionsupport_1_11_R1/src/main/java/com/andrei1058/bedwars/support/version/v1_11_R1/v1_11_R1.java
  versionsupport_1_12_R1/src/main/java/com/andrei1058/bedwars/support/version/v1_12_R1/v1_12_R1.java
  versionsupport_1_13_R2/src/main/java/com/andrei1058/bedwars/support/version/v1_13_R2/v1_13_R2.java
  versionsupport_1_14_R1/src/main/java/com/andrei1058/bedwars/support/version/v1_14_R1/v1_14_R1.java
  versionsupport_1_15_R1/src/main/java/com/andrei1058/bedwars/support/version/v1_15_R1/v1_15_R1.java
  versionsupport_1_8_R3/src/main/java/com/andrei1058/bedwars/support/version/v1_8_R3/v1_8_R3.java
  versionsupport_1_9_R2/src/main/java/com/andrei1058/bedwars/support/version/v1_9_R2/v1_9_R2.java
Labels: under-review, needs-testing
